extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  source-type: 'module'
  ecmaVersion: 10
plugins:
  - '@typescript-eslint'
env:
  node: true
  browser: true
rules:
  object-curly-spacing:
    - error
    - 'always'
  quotes:
    - error
    - 'single'
  semi:
    - error
    - 'never'
  no-trailing-spaces:
    - error